baseurl = "/"
languageCode = "en-us"
title = "TUC C&Y Ministry"

[params]
  description = "(https://github.com/eliwilliamson) and cloned by anapitalai@gmail.com"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Profile"
    url  = "/profile"
    weight = 2
[[menu.main]]
    name = "Program"
    url  = "/program"
    weight = 3
[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 4
[[menu.main]]
    name = "Feedback"
    url  = "/contact"
    weight = 5
