baseurl = "/"
languageCode = "en-us"
title = "TUC C&YM"

[params]
  description = "(https://github.com/eliwilliamson) and cloned by anapitalai@gmail.com"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 2
